AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to create a lambda function

Parameters:
  LambdaFunctionName:
    Type: String
    Default: ka-me-ha-me-ha-enabler
    Description: Enter the name of the lambda function

Resources:
  MyLambdaEnabler:
    Type: AWS::Lambda::Function
    Properties:
      Role: 
        Fn::ImportValue: !Sub MyLambdaRoleArn-s3-Ddb
      Runtime: python3.12
      Handler: app.lambda_handler
      FunctionName: !Ref LambdaFunctionName
      Codeuri: Lambda/app.py
      Description: This is a lambda function for adding a object in s3 bucket.
  


  MyEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 100
      FunctionName: !Ref    MyLambdaEnabler
      EventSourceArn: 
        Fn::ImportValue: !Sub MyGlobalTableArn
      StartingPosition: "LATEST"

Outputs:
  LambdaFunctionArn:
    Description: "ARN of the Lambda function"
    Value: !GetAtt MyLambdaEnabler.Arn