AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SAM Template for Lambda Function and Event Source Mapping Stack

Resources:
  MyLambdaEnabler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      Handler: app.lambda_handler
      FunctionName: ka-me-ha-me-ha-enabler
      CodeUri: Lambda/
      Description: This is a lambda function for adding an object in the S3 bucket.
      Role: !ImportValue LambdaRoleArn

  MyEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    DependsOn: MyLambdaEnabler
    Properties:
      BatchSize: 100
      FunctionName: !Ref MyLambdaEnabler
      EventSourceArn: !ImportValue GlobalTableStreamArn
      StartingPosition: "LATEST"

Outputs:
  LambdaFunctionArn:
    Description: "ARN of the Lambda function"
    Value: !GetAtt MyLambdaEnabler.Arn
